<!-- Footer -->

    <footer class="footer">
      <div class="footer-container">
        <div class="footer-row">
          <div class="footer-co">
            <h4 id="website">Website</h4>
            <ul>
              <li><a href="about.php">about us</a></li>
              <li><a href="about.php">our services</a></li>
              <li><a href="about.php">job policy</a></li>
            </ul>
          </div>
          <div class="footer-co">
            <h4 id="help">help</h4>
            <ul>
              <li><a href="#">FAQ</a></li>
              <li><a href="#">refunds</a></li>
              <li><a href="apply.php">Job status</a></li>
              <li><a href="#">payment options</a></li>
            </ul>
          </div>
          <div class="footer-co">
            <h4 id="member">Memberships</h4>
            <ul>
              <li><a href="#">free trial</a></li>
              <li><a href="#">basic option</a></li>
              <li><a href="#">long-term plan</a></li>
              <li><a href="#">premium access</a></li>
            </ul>
          </div>
          <div class="footer-co">
            <h4 id="follow">follow us</h4>
            <div class="social-links">
              <a href="https://www.facebook.com/" target="_blank">
                <i class="fab fa-facebook-f" aria-hidden="true"></i>
                <span class="sr-only">Visit our Facebook page</span>
              </a>
              <a href="https://twitter.com/?lang=en" target="_blank"
                ><i class="fab fa-twitter" aria-hidden="true"></i
                ><span class="sr-only">Visit our Twitter page</span></a
              >
              <a href="https://www.instagram.com/" target="_blank"
                ><i class="fab fa-instagram" aria-hidden="true"></i
                ><span class="sr-only">Visit our Instagram page</span></a
              >
              <a href="https://www.linkedin.com/" target="_blank"
                ><i class="fab fa-linkedin-in" aria-hidden="true"></i
                ><span class="sr-only">Visit our Linkedin page</span></a
              >
            </div>
          </div>
        </div>
      </div>
    </footer>

