      <nav id="nav-for-desktop">
        <!-- Main navigation bar -->
        <div class="col12 s-col12 col" id="div-nav-main">
          <div id="main-nav" class="col9 s-col9 col">
            <a href="index.html"
              ><img src="images/logo.png" alt="job-hunting-icon"
            /></a>
            <ul>
              <li>
                <a href="#"><span>Home</span></a>
              </li>
              <li>
                <a href="jobs.html"><span>Potential jobs</span></a>
              </li>
              <li>
                <a href="about.html"><span>Companies</span></a>
              </li>
              <li>
                <a href="#"><span>Login</span></a>
              </li>
            </ul>
          </div>
          <!-- Sub navigation bar  -->
          <div id="sub-nav" class="col2 s-col2 col">
            <ul>
              <li>
                <a href="enhancements.html">Enhance</a>
              </li>
              <li>
                <a href="apply.html" target="_blank">Apply your cv</a>
              </li>
              <li><a href="about.html">About us</a></li>
            </ul>
          </div>
        </div>
      </nav>
      <!-- Nav for smaller screen size -->
      <nav id="nav-for-tablet">
        <a href="index.html"><img src="images/logo.png" alt="logo" /></a>
        <div class="dropdown">
          <div>Menu</div>
          <div class="dropdown-content">
            <a href="index.html">Home</a> <br />
            <a href="jobs.html">Potential Jobs</a><br />
            <a href="about.html">Companies</a><br />
            <a href="enhancements.html">Enhance</a><br />
            <a href="#">Login</a><br />
          </div>
        </div>
      </nav>